[mypy]
# Python version for type checking
disallow_subclassing_any = False
python_version = 3.12

# Use a strict mode for full type safety
strict = True

# Allow type hints to be used from untyped third-party packages
ignore_missing_imports = true


# Report unused 'type: ignore' comments
warn_unused_ignores = true


# Useful if you’re in a monorepo or hexagonal setup
namespace_packages = true

show_error_codes = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_untyped_calls = True
check_untyped_defs = True